services:
  postgres:
    image: postgres
    env_file:
      - ./.env.postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    env_file:
      - ./.env.redis
    ports:
      - 6379:6379
    command: "redis-server --requirepass $REDIS_PASSWORD"

volumes:
  pgdata: {}
